config/routes.rb
Rails.application.routes.draw do
# Aboutページ
  root "top#index"
  get    "/login",   to: "sessions#new", as: :login
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :articles do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # カテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_categories/:id/show', to: "articles#category",  as: :category
  # サイドバーカテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_category/:id/:name', to: "articles#each_category",  as: :each_category
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  # userと関連
  belongs_to :user
  # articleと関連
  belongs_to :article
  # 空でないこと
  validates :content, presence: true
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    # 慣習的に関連するモデルを生成するときは、buildを使うnewとの違いはない
    @article_comment = @article.article_comments.build(article_comment_params)
    @article_comment.user_id = current_user.id
    if @article_comment.save
      render :index
    end
  end

  def destroy
    @article_comment = ArticleComment.find(params[:id])
    if @article_comment.destroy
      render :index
    end
  end

  private
  def article_comment_params
    params.require(:article_comment).permit(:content, :article_id, :user_id)
  end
end

app/views/article_comments/_form.html.erb
<% if logged_in? %>
<div>
  <%= form_with(model: [article, article_comment] ) do |form| %>
    <div class="">
      <%= form.text_area :content, class: "article_comment_area" %>
    </div>
    <div class="actions">
      <%= form.submit "Comment", class: "button" %>
    </div>
  <% end %>
</div>
<% end %>

app/views/article_comments/_index.html.erb
<div id="article_comments_area">
  <% article_comments.each do |article_comment| %>
    <% unless article_comment.id.nil? %>
    <div>
      <span><%= "@#{article_comment.user.name}さん(; ･`д･´)φメモメモ" %></span>
      <p><%= toc(article_comment.content) %><%= markdown(article_comment.content) %></p>
    </div>
      <% if article_comment.user == current_user %>
        <p><%= link_to 'Delete', article_article_comment_path(article_comment.article_id, article_comment.id), method: :delete, remote: true, id: "delete_button" %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/article_comments/index.js.erb
$("#article_comments_area").html("<%= j(render 'index', { article_comments: @article_comment.article.article_comments }) %>")
$("textarea").val('')