config/routes.rb
Rails.application.routes.draw do
# Aboutページ
  root "top#index"
  get    "/login",   to: "sessions#new", as: :login
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :articles do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # カテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_categories/:id/show', to: "articles#category",  as: :category
  # サイドバーカテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_category/:id/:name', to: "articles#each_category",  as: :each_category
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: { message: 'タイトルが空欄だよ？' }
  validates :description, presence: { message: '本文が空欄だよ？' }
  # ユーザーと関連
  belongs_to :user
  # 多くの記事コメントを持つ、諸共削除
  has_many :article_comments, dependent: :destroy
  # タイトル検索用メソッド
  has_many :favorites
  #　カテゴリー
  has_many :article_category_relations
  has_many :article_categories, through: :article_category_relations
  # 渡した配列に含まれているIDを持つ他の記事を探してくる
  scope :category_id_in, -> article_category_ids {
    joins(:article_categories).merge(ArticleCategory.id_in article_category_ids)
  }

  def self.create_all_ranks # articleクラスからデータを取ってくる処理なのでクラスメソッド！
    Article.find(Favorite.group(:article_id).order('count(article_id) desc').limit(3).pluck(:article_id))
  end

  def self.search(search)
    return Article.all.order(created_at: :desc) unless search
    Article.where(['title LIKE ?', "%#{search}%"],)
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [
    :show, :edit, :update, :destroy, :category]
  before_action :logged_in_user, only: [
    :new ,:create, :edit, :update, :destroy]
  before_action :correct_user, only: [
    :edit, :update, :destroy]

  def index                              # 記事一覧画面
    @article = Article.new
    #　検索フォーム
    @articles = Article.search(params[:search])
    # ページネーション
    @articles = @articles.page(params[:page])
    # 記事一覧
    @side_articles = Article.all
    # ランキング
    @all_ranks = Article.create_all_ranks
    # カテゴリー
    @categories = ArticleCategory.all
    if logged_in?
      # 自分のランキング
      @my_ranks = @all_ranks.select{ |article| article.user_id == current_user.id }
    end
  end

  def show                               # 記事表示画面
    # コメント
    @article_comment = ArticleComment.new
    @article_comments = @article.article_comments
    #　検索フォーム
    @articles = Article.search(params[:search])
    # 記事一覧
    @side_articles = Article.all
    # ランキング
    @all_ranks = Article.create_all_ranks
    # カテゴリー
    @categories = ArticleCategory.all
    if logged_in?
      # 自分のランキング
      @my_ranks = @all_ranks.select{ |article| article.user_id == current_user.id }
    end
  end

  def category
    @ids = @article.article_categories.ids
    # 上記配列に含まれているIDを持つ他の記事を探してくる
    @article_category_id_in = Article.category_id_in(@ids)
    @articles = Article.search(params[:search])
    # ページネーション
    @articles = @articles.page(params[:page])
    # ランキング
    @all_ranks = Article.create_all_ranks
    if logged_in?
      # 自分のランキング
      @my_ranks = @all_ranks.select{ |article| article.user_id == current_user.id }
    end
  end

  def each_category
    @name = ArticleCategory.find(params[:id])
    # 上記のIDを持つ他の記事を探してくる
    @article_category_id_in = Article.category_id_in(@name)
    @articles = Article.search(params[:search])
    # ページネーション
    @articles = @articles.page(params[:page])
    # ランキング
    @all_ranks = Article.create_all_ranks
    # カテゴリー
    @categories = ArticleCategory.all
    if logged_in?
      # 自分のランキング
      @my_ranks = @all_ranks.select{ |article| article.user_id == current_user.id }
    end
  end

  def edit                               # 記事編集画面
  end

  def new                                # 記事作成画面
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash.notice = "記事「#{@article.title}」作成したよ！( *´艸｀)"
      redirect_to @article
    else
      flash.now.alert = "登録に失敗しました！"
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash.notice = "記事を更新したよ！( *´艸｀)"
      redirect_to @article
    else
      @articles = Article.all
      @user = User.find(current_user.id)
      flash.now.alert = "登録に失敗しました！"
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash.notice = "綺麗に消せたよ！( *´艸｀）"
    redirect_to user_path(current_user)
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  # チェックボックスによって複数渡される場合があるため、配列ids: []
  def article_params
    params.require(:article).permit(:title,
      :description, article_category_ids: [])
  end

  def article_category_params
    params.require(:article_category).permit(:name)
  end

  def logged_in_user
    unless logged_in?
      flash.notice = "ログインして下さい"
      redirect_to login_url
    end
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = @article.user
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/views/articles/_category.html.erb
<% article.article_categories.each do |category| %>
  <span class="article-category">#<%= link_to category.name, category_path(article), class: "article-category-button" %></span>
<% end %>

app/views/articles/_favorite.html.erb
<!-- いいね機能 -->
<div class="article_<%= article.id %>">
  <!-- いいね機能 -->
  <% if current_user %>
    <% if article.favorited_by?(current_user) %>
      <%= link_to article_favorites_path(article, redirect_id: 0), method: :delete, remote: true do %>
        <span class="iine">(; ･`д･´)☆素敵!<%= article.favorites.count %></span>
      <% end %>
    <% else %>
      <%= link_to article_favorites_path(article, redirect_id: 0), method: :post, remote: true do %>
        <span class="iine-no">(; ･`д･´)★<%= article.favorites.count %></span>
      <% end %>
    <% end %>
  <% else %>
    (・∀・)ｲｲﾈ!!☆<%= article.favorites.count %>
  <% end %>
</div>

app/views/articles/_my_ranking.html.erb
<!-- 自分の評価したランキング -->
<% if current_user %>
  <div class="my_ranking_side_index">
    <% my_ranks.each.with_index(1) do |article, i| %>
      <%= "☆お気に入り記事 #{i}位" %>
      <li><%= link_to article.title, article %></li>
    <% end %>
  </div>
<% end %>

app/views/articles/_ranking.html.erb
<!-- ランキング -->
<div class="ranking_side_index">
  <% all_ranks.each.with_index(1) do |article, i| %>
    <%= "☆素敵度 #{i}位" %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</div>

app/views/articles/_search.html.erb
<h4>記事検索</h4>
<%= form_tag(articles_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil, class: "button_search"%>
<% end %>
<h4 class="iine">最新記事</h4>
<% articles.each do |article| %>
  <li><%= link_to article.title, article %></li>
<% end %>

app/views/articles/_side_categories.html.erb
<div class="category-side-index">
  <h4 class="category-title"><%= link_to "カテゴリー", articles_path %></h4>
  <% @categories.each do |category| %>
    <li class="category-index"># <%= link_to "#{category.name}",each_category_path(id: category,name: "#{category.name}") %></li>
  <% end %>
</div>

app/views/articles/_side_index.html.erb
<h4><%= link_to "記事一覧", :articles, class: "header_button" %></h4>
<% side_articles.each do |article| %>
  <li><%= link_to article.title, article %></li>
<% end %>

app/views/articles/category.html.erb
<div class="container">
  <div class="container-article">
    <%  @article_category_id_in.each do |article| %>
      <h3 class="article_title"><%= link_to article.title, article_path(article) %></h3><p>
      <div class="article_body"><%= markdown(article.description).html_safe %></div>
      <div class="comment">
        コメント数: <%= ArticleComment.where(article_id: article.id).count %>
        <!-- いいね機能 -->
        <%= render 'articles/favorite', article: article %>
        <!-- カテゴリー -->
        <% article.article_categories.each do |category| %>
          <span class="article-category">#<%= category.name %></span>
        <% end %>
      </div>
    <% end %>
    <div><hr>
      <!-- ページネーション -->
      <%= paginate @articles %>
    </div>
  </div>
  <div class="container_index">
    <%= render "shared/sns" %>
    <!-- 検索フォーム -->
    <%= render "articles/search", articles: @articles %>
    <!-- ランキング -->
    <%= render "articles/ranking", all_ranks: @all_ranks %>
    <!-- カテゴリー -->


    <% if current_user %>
      <!-- 自分の評価したランキング -->
      <%= render "articles/my_ranking", my_ranks: @my_ranks %>
    <% end %>
  </div>
</div>

app/views/articles/each_category.html.erb
<div class="container">
  <div class="container-article">
    <%  @article_category_id_in.each do |article| %>
      <h3 class="article_title"><%= link_to article.title, article_path(article) %></h3><p>
      <div class="article_body"><%= markdown(article.description).html_safe %></div>
      <div class="comment">
        <!-- コメントカウント -->
        コメント数: <%= ArticleComment.where(article_id: article.id).count %>
        <!-- いいね機能 -->
        <%= render 'articles/favorite', article: article %>
        <!-- カテゴリー -->
        <%= render 'articles/category', article: article %>
      </div>
    <% end %>
    <div><hr>
      <!-- ページネーション -->
      <%= paginate @articles %>
    </div>
  </div>
  <div class="container_index">
    <!-- SNS共有 -->
    <%= render "shared/sns" %>
    <!-- 検索フォーム -->
    <%= render "articles/search", articles: @articles %>
    <!-- ランキング -->
    <%= render "articles/ranking", all_ranks: @all_ranks %>
    <!-- 自分の評価したランキング -->
    <%= render "articles/my_ranking", my_ranks: @my_ranks %>
    <!-- カテゴリー -->
    <%= render 'articles/side_categories', categories: @categories %>
  </div>
</div>

app/views/articles/edit.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li class="errors"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
	<%= form_with model: @article, local: true do |f| %>
		<p><%= f.label :タイトル %></p>
		<p><%= f.text_field :title, class: "text_field_title" %></p>
		<p><%= f.label :記事 %></p>
		<p><%= f.text_area :description %></p>
		<p><hr>
		<%= f.label :article_category, 'カテゴリ' %><br>
		<%= f.collection_check_boxes(:article_category_ids, ArticleCategory.all, :id, :name) do |category| %> 
			<%= category.label do %>
				<%= category.check_box %>
				<%= category.text %>
			<% end %>
		<% end %>
		</p>
		<p><%= f.submit class: "button" %></p>
	<% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="container-article">
    <% @articles.each do |article| %>
      <h3 class="article_title"><%= link_to article.title, article_path(article) %></h3>
      <div class="article_body"><%= toc(article.description) %><%= markdown(article.description) %></div>
      <div class="comment">
      　<!-- コメントカウント -->
        コメント数: <%= ArticleComment.where(article_id: article.id).count %>
        <!-- いいね機能 -->
        <%= render 'articles/favorite', article: article %>
        <!-- カテゴリー -->
        <%= render 'articles/category', article: article %>
      </div>
    <% end %>
    <div><hr>
      <!-- ページネーション -->
      <%= paginate @articles %>
    </div>
  </div>
  <div class="container_index">
    <!-- SNS共有 -->
    <%= render "shared/sns" %>
    <!-- 検索フォーム -->
    <%= render "articles/search", articles: @articles %>
    <!-- ランキング -->
    <%= render "articles/ranking", all_ranks: @all_ranks %>
    <!-- 自分の評価したランキング -->
    <%= render "articles/my_ranking", my_ranks: @my_ranks %>
    <!-- カテゴリー -->
    <%= render 'articles/side_categories', categories: @categories %>
    <!-- 記事一覧 -->
    <%= render "articles/side_index", side_articles: @side_articles%>
  </div>
</div>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li class="errors"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
 <div class="container">
  <%= form_with model: @article, url: :articles, local: true do |f| %>
    <p><%= f.label :タイトル %></p>
    <p><%= f.text_field :title, class: "text_field_title" %></p>
    <p><%= f.label :記事 %></p>
    <p><%= f.text_area :description %></p>
    <p><hr>
    <%= f.label :article_category, 'カテゴリ' %><br>
    <%= f.collection_check_boxes(:article_category_ids, ArticleCategory.all, :id, :name) do |category| %> 
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
    </p>
    <p><%= f.submit "登録する", class: "button" %></p>
  <% end %>
</div> 

app/views/articles/show.html.erb
<div class="container">
  <div class="container-article">
    <h3 class="article_title"><%= @article.title %></h3>
    <div class="article_body_show"><%= toc(@article.description) %><%= markdown(@article.description) %></div><hr>
    <div class="comment">
      <!-- コメントカウント -->
      コメント数: <%= ArticleComment.where(article_id: @article.id).count %>
      <!-- いいね機能 -->
      <%= render 'articles/favorite', article: @article %>
      <!-- カテゴリー -->
      <%= render 'articles/category', article: @article %>
  </div>
    <!-- 投稿されたコメント一覧を表示 -->
    <%= render partial: 'article_comments/index', locals: { article_comments: @article_comments } %>
  　<!-- コメント入力欄 -->
    <%= render partial: 'article_comments/form', locals: { article_comment: @article_comment, article: @article } %>
  </div>
  <div class="container_index">
    <!-- SNS共有 -->
    <%= render "shared/sns" %>
    <!-- 検索フォーム -->
    <%= render "articles/search", articles: @articles %>
    <!-- ランキング -->
    <%= render "articles/ranking", all_ranks: @all_ranks %>
    <!-- 自分の評価したランキング -->
    <%= render "articles/my_ranking", my_ranks: @my_ranks %>
    <!-- カテゴリー -->
    <%= render 'articles/side_categories', categories: @categories %>
    <!-- 記事一覧 -->
    <%= render "articles/side_index", side_articles: @side_articles%>
  </div>
</div>