config/routes.rb
Rails.application.routes.draw do
# Aboutページ
  root "top#index"
  get    "/login",   to: "sessions#new", as: :login
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users
  resources :articles do
    resources :article_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  # カテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_categories/:id/show', to: "articles#category",  as: :category
  # サイドバーカテゴリータグ移行先のそのタグが含まれる記事が表示されるページ
  get '/article_category/:id/:name', to: "articles#each_category",  as: :each_category
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  validates :name, presence: { message: 'が空欄だよ？' }
  validates :email, presence: { message: 'が空欄だよ？' }
  validates :password, presence: { message: 'きゃんとびいぶらんく☆' }
  has_secure_password
  # 多くの記事と関連、諸共削除
  has_many :articles, dependent: :destroy
  # 多くの記事コメントと関連、諸共削除
  has_many :article_comments, dependent: :destroy
  has_many :favorites

  # 与えられた文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークン
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  end

  # ユーザーログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [
    :show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [
    :show, :edit, :update, :destroy]
  before_action :correct_user, only: [
    :show, :edit, :update]

  def index
    @users = User.all
  end

  def show                               # user詳細画面
    @article = Article.new
  end

  def new                                #　新規登録画面
    @user = User.new
  end

  def edit
  end

  def create                             # 新規登録
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash.notice = "登録完了しました！"
      redirect_to @user
    else
      flash.now.alert = "登録に失敗しました！"
      render 'new'
    end
  end

  def update
     if @user.update_attributes(user_params)
      flash.notice = "登録完了しました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.notice = "削除しました！"
    redirect_to users_url
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash.notice = "ログインして下さい"
      redirect_to login_url
    end
  end
  # 正しいユーザーかどうか確認
  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- エラーメッセージ -->
<%= render 'shared/error_messages', user: @user %>
<div class="container">
  <div class="container-article">
    <h1>アカウント情報編集</h1>
    <%= form_with model: @user, local: true do |f| %>
          <p><%= f.label :name %></p>
          <p><%= f.text_field :name %></p>
          <p><%= f.label :email %></p>
          <p><%= f.email_field :email %></p>
          <p><%= f.label :password %></p>
          <p><%= f.password_field :password %></p>
          <p><%= f.label :password %></p>
          <p><%= f.password_field :password_confirmation %></p>
          <p><%= f.submit "変更する", class: "button" %></p>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container_show">
<table class="user-edit-table">
  <tbody>
    <tr>
      <td><%= "ニックネーム  #{current_user.name}" %></td>
    </tr>
      <td><%= "メールアドレス  #{current_user.email}" %></td>
    <tr>
    </tr>
  </tbody>
</table>
</div>
<div class="container_show">
  <% @users.each do |user| %>
    <div class="container-article">
        <table class="user-edit-table">
  <tbody>
    <tr>
      <td><%= "ニックネーム  #{user.name}" %></td>
    </tr>
      <td><%= "メールアドレス  #{user.email}" %></td>
    <tr>
    </tr>
  </tbody>
</table>
    </div>
    <%= link_to "編集", user_path(user), class: "button" %>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to "delete", user, method: :delete, data: { confirm: "本当にいいの?" } %>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="errors"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  <div class="container-article">
    <h1>新規登録</h1>
    <%= form_with model: @user, url: :users, local: true do |f| %>
          <p><%= f.label :name %></p>
          <p><%= f.text_field :name %></p>
          <p><%= f.label :email %></p>
          <p><%= f.email_field :email %></p>
          <p><%= f.label :password %></p>
          <p><%= f.password_field :password %></p>
          <p><%= f.label :password %></p>
          <p><%= f.password_field :password_confirmation %></p>
          <p><%= f.submit "登録", class: "button" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container_show">
<table class="user-edit-table">
  <tbody>
    <tr>
      <td><%= "ニックネーム  #{@user.name}" %></td>
    </tr>
      <td><%= "メールアドレス  #{@user.email}" %></td>
    <tr>
    </tr>
  </tbody>
</table>
<%= link_to "アカウント情報を変更する", edit_user_path(current_user), class: "button" %>
</div>
<div class="container_show">
  <% @user.articles.each do |article| %>
    <div class="container-article">
        <h3 class="article_title"><%= link_to article.title, article_path(article) %></h3>
        <div class="article_body"><%= markdown(article.description).html_safe %></div>
    </div>
    <%= link_to "編集", edit_article_path(article), class: "button" %>
    <%= link_to "削除", article_path(article), method: :delete, date:
        { confirm: "「#{article.title}」を消すよ。本当にいいの( *´艸｀)？"}, class: "button"%>
    <%= link_to "記事を書く", :new_article, class: "button" %>
  <% end %>
</div>
<div class="alticle-write"><%= link_to "記事を書く", :new_article, class: "button" %></div>